### ISSUE TITLE
Kiam 2.7 doesn't build

### ISSUE THREAD

**Issue by kylehodgetts** [uswitch/kiam#65]
Steps:
`git clone git@github.com:uswitch/kiam.git --branch 2.7-deploy`
` cd kiam`
` make`

When running `make` in the project root, this is the ouput:

```
# github.com/uswitch/kiam/pkg/server
pkg/server/server.go:187: cannot use server (type *KiamServer) as type kiam.KiamServiceServer in argument to ServerWithTelemetry:
	*KiamServer does not implement kiam.KiamServiceServer (wrong type for GetHealth method)
		have GetHealth("context".Context, *kiam.GetHealthRequest) (*kiam.HealthStatus, error)
		want GetHealth("github.com/uswitch/kiam/vendor/golang.org/x/net/context".Context, *kiam.GetHealthRequest) (*kiam.HealthStatus, error)
pkg/server/telemetry.go:30: cannot use TelemetryClient literal (type *TelemetryClient) as type kiam.KiamServiceClient in return argument:
	*TelemetryClient does not implement kiam.KiamServiceClient (wrong type for GetHealth method)
		have GetHealth("context".Context, *kiam.GetHealthRequest, ...grpc.CallOption) (*kiam.HealthStatus, error)
		want GetHealth("github.com/uswitch/kiam/vendor/golang.org/x/net/context".Context, *kiam.GetHealthRequest, ...grpc.CallOption) (*kiam.HealthStatus, error)
pkg/server/telemetry.go:71: cannot use TelemetryServer literal (type *TelemetryServer) as type kiam.KiamServiceServer in return argument:
	*TelemetryServer does not implement kiam.KiamServiceServer (wrong type for GetHealth method)
		have GetHealth("context".Context, *kiam.GetHealthRequest) (*kiam.HealthStatus, error)
		want GetHealth("github.com/uswitch/kiam/vendor/golang.org/x/net/context".Context, *kiam.GetHealthRequest) (*kiam.HealthStatus, error)
make: *** [bin/agent] Error 2
```

**Comment by Joseph-Irving** [comment]
Hi,

Can you confirm what version of Go you're using? I can reproduce this with 1.8. 
Kiam is built with go 1.9 so anything above that should work.

**Comment by mikesplain** [comment]
Works fine in `go1.10.2` for me.

**Comment by kylehodgetts** [comment]
That would be it. I'm using go version 1.8.2

**Comment by pingles** [comment]
Cool- I'll add a note in the README to use 1.9+.

**Comment by kylehodgetts** [comment]
Thanks for the prompt responses guys 👍
